language: objective-c
osx_image: xcode11.6
xcode_project: WeatherVIP.xcodeproj
xcode_scheme: WeatherVIP
xcode_sdk: iphonesimulator13.6
xcode_destination: 'platform=iOS Simulator,name=iPhone 6,OS=9.3'

#
