language: objective-c
osx_image: xcode11.6
xcode_project: WeatherVIP.xcodeproj
xcode_scheme: WeatherVIP
xcode_sdk: iphonesimulator13.6

script: xctool -project WeatherVIP.xcodeproj -scheme WeatherVIP build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#script:
#- xcodebuild CODE_SIGNING_REQUIRED=NO -allowProvisioningUpdates
#xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone X
